### ISSUE TITLE
All downloaded images can't be opened

### ISSUE THREAD

**Issue by xmezzaluna** [nakrovati/fapeloader#1]
For some reason, the downloaded images are downloaded from unavailable link from fapello, I tried it using username malena-cherry on fapello, and the links provided from the app are either obsolete or unavailable.
Then I checked manually on fapello, and the link they provided are a bit different, the difference is in the file name:
.../malena-cherry_1.jpg -> from app
.../malena-cherry_0001.jpg -> from the web
I believe that's what making the image can't be opened
![test](https://github.com/nakrovati/fapesnap/assets/61771214/b87add09-5af0-4959-8812-db931d1dfb76)

**Comment by nakrovati** [comment]
Hi, thanks for writing. It looks like fapello changed the URL structure of the photos and the app wasn't tracking that they didn't exist. I made a hotfix, so you can use it.
